version: "2"
services:
    db:
        image: mysql:5.7
        ports: 
            - 3306:3306
        environment:
            MYSQL_DATABASE: app
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root 
        volumes:
            - ./initdb.d:/docker-entrypoint-initdb.d
            - db-data:/var/lib/mysql
        networks:
            - default

    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        links: 
            - db:db
        ports:
            - 8001:80
        environment:
            MYSQL_USER: user
            MYSQL_PASSWORD: password
            MYSQL_ROOT_PASSWORD: root 

    www:
        build: .
        ports: 
            - 8000:80
        volumes:
            - ./www:/var/www/html/
        links:
            - db
        networks:
            - default
volumes:
    db-data:
